# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b227d92c09571ef04ed15f11f75ce64c59260a08e6e29313f3a670e44aba4756f2d03fb93f1e780a85a524ab13212a1edba148acc6ce13d0547221f70e356ae

test:
  secret_key_base: 0057df1ccef9ec5320c6726ea26866cfe8f730272bde24abf03583b0864616fc0cb225df52ec8d6b8ea5116b0104a4ec8a1bd374f4f765269ecc77fb2f763512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
